version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=warehouse1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
